config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  root 'products#index'
  resources :products
  resource :cart, only: [:show, :update, :destroy,:create]
  get 'check_cart', to: 'carts#check_cart'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :products, through: :cart_items
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :admin
  belongs_to :product

  validates :product_id, uniqueness: { scope: :admin_id }
end

app/models/product.rb
# frozen_string_literal: true

# class for product model
class Product < ApplicationRecord
  has_many :cart_items
  has_many :admins, through: :cart_items
  # this for not added empty data
  validates :product_name, presence: true, uniqueness: true
  validates :description, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# Class for Application controller
class ApplicationController < ActionController::Base
  before_action :authenticate_admin!
end

app/controllers/carts_controller.rb
# frozen_string_literal: true

# Class for Products controller
class CartsController < ApplicationController
  before_action :authenticate_admin!

  def show
    @cart_items = current_admin.cart_items.includes(:product)
  end

  def create
    product = Product.find(params[:product_id])
    cart_item = current_admin.cart_items.find_or_initialize_by(product: product)
    cart_item.quantity = cart_item.quantity.to_i + 1
    cart_item.save
    redirect_to cart_path, notice: 'Product added to cart.'
  end

  def destroy
    cart_item = current_admin.cart_items.find_by(product_id: params[:product_id])
    cart_item&.destroy
    redirect_to cart_path, notice: 'Product remove from cart.'
  end

  def update
    cart_item = current_admin.cart_items.find_by(product_id: params[:product_id])
    if cart_item && params[:quantity].to_i.positive?
      cart_item.update(quantity: params[:quantity])
    elsif cart_item
      cart_item.destroy
    end
    redirect_to cart_path
  end
  def check_cart
    if current_admin.cart_items.any?
      redirect_to cart_path
    else
      redirect_to products_path, notice: 'Cart is empty, please add items.'
    end
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

# Class for Products controller
class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy]

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def show
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to products_path, notice: ' Product was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to products_path, notice: 'Product was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    puts "....................................."

    respond_to do |format|
      format.html { redirect_to products_url, notice: 'User was successfully destroyed.' }
    end
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:product_name, :description, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/carts/show.html.erb
<h1>Cart</h1>

<% if @cart_items.any? %>
  <table>
    <thead>
      <tr>
        <th>Product</th>
        <th>Quantity</th>
        <th>Price</th>
        <th>Total</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% total_price = 0 %>
      <% @cart_items.each do |cart_item| %>
        <tr>
          <td><%= cart_item.product.product_name %></td>
          <td>
            <%= form_with url: cart_path(product_id: cart_item.product.id), method: :patch, local: true do %>
              <%= number_field_tag :quantity, cart_item.quantity, min: 1 %>
              <%= submit_tag 'Update' %>
            <% end %>
          </td>
          <td><%= number_to_currency(cart_item.product.price) %></td>
          <td><%= number_to_currency(cart_item.product.price * cart_item.quantity) %></td>
          <% total_price += cart_item.product.price * cart_item.quantity %>
          <td>
            <%= button_to 'Remove', cart_path(product_id: cart_item.product.id), method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
  <div class="total-price">
    <h2>Total Price: <%= number_to_currency(total_price) %> <%= button_to 'Buy Now' %></h2>
  </div>

<% else %>
  <p>Your cart is empty.</p>
<% end %>

<%= link_to 'Back to products', products_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ecommerce</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <% if admin_signed_in? %>
      logged in as <strong><%= current_admin.email %></strong>.
      <%= link_to "Edit Profile", edit_admin_registration_path %>
      <%= link_to "Log out", destroy_admin_session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign up", new_admin_registration_path %> or 
      <%= link_to "Login", new_admin_session_path %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/products/edit.html.erb
<h1>New Product</h1>
<%= form_with model: @product, local: true do |form| %>
 <div>
     <%= form.label :product_name %>
     <%= form.text_field :product_name %>
   </div>
   <div>
     <%= form.label :description %>
     <%= form.text_area :description %>
   </div>
   <div>
     <%= form.label :price %>
     <%= form.number_field :price %>
   </div>
   <%= form.submit 'update Product' %>
<% end %>
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Products</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.product_name %></td>
        <td><%= product.description %></td>
        <td><%= number_to_currency(product.price) %></td>
        <td><%= link_to 'Show', product_path(product) %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to "Destroy", product_path(product), method: :delete%></td>
        <td><%= button_to 'Add to Cart', cart_path(product_id: product.id), method: :post %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'New Product', new_product_path %>
<%= button_to 'Go to Cart', check_cart_path, method: :get, class: 'cart-button' %>

app/views/products/new.html.erb
<h1>New Product</h1>
<%= form_with model: @product, local: true do |form| %>
    <div>
      <%= form.label :product_name %>
      <%= form.text_field :product_name %>
    </div>
    <div>
      <%= form.label :description %>
      <%= form.text_area :description %>
    </div>
    <div>
      <%= form.label :price %>
      <%= form.number_field :price %>
    </div>
    <%= form.submit 'Create Product' %>
<% end %>
<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<h1>Product details</h1>
<p><strong>Product</strong><%= @product.product_name %></p>
<p><strong>details</strong><%= @product.description %></p>
<p><strong>Price</strong><%= number_to_currency(@product.price) %></p>
<%= button_to 'Add to Cart', cart_path(product_id: @product.id), method: :post %>
<%= link_to 'Edit', edit_product_path%>
<%= link_to "Destroy", product_path(@product), method: :delete %>
<%= link_to 'Back', products_path %>